package org.example;

public enum UserState {
    ////////Menu/////////
    START,
    STAGE_1_CHOSE_NUM_OF_QUESTION,
    STAGE_2_SEND_NUM_OF_OPTIONS,
    STAGE_3_CHOSE_NUM_OF_OPTIONS,
    STAGE_4_ADD_QUEST_OR_OPTIONS,
    STAGE_5_SELECT_TIME_TO_SEND,
    STAGE_6_CHOSE_MINUTES,
    STAGE_7_WAIT_FOR_RESULTS,


}
